queue:
  name: Hosted VS2017
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack

    packagesToPack: LeoPetri.Common/LeoPetri.Common.csproj


- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push

    nuGetFeedType: external

    publishFeedCredentials: LeoPetri.Common

