variables:
  PackageVersion: '1.0.0'
  VersionBuildNumber: $[counter('$(PackageVersion)', 1)]
  PreReleaseVersion: $(PackageVersion).$(VersionBuildNumber)

queue:
  name: Hosted VS2017

trigger:
  - master

steps:
- script: |
    dotnet build
    dotnet test tests/LeoPetri.Common.Functions.UnitTest --logger trx

  displayName: 'build and test LeoPetri.Common.Functions'
  
- task: PublishTestResults@2
  condition: succeededOrFailed()
  displayName: 'publish tests'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/**/*.trx'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack Common.Functions'
  inputs:
    command: pack
    packagesToPack: src/LeoPetri.Common.Functions/LeoPetri.Common.Functions.csproj
    versioningScheme: byEnvVar
    versionEnvVar: PreReleaseVersion
    
- task: NuGetCommand@2
  displayName: 'NuGet push Common'
  continueOnError: true
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: LeoPetri.Common