variables:
  PackageVersion: '2.0.1'
  VersionBuildNumber: $[counter('$(PackageVersion)', 1)]
  PreReleaseVersion: $(PackageVersion).$(VersionBuildNumber)

queue:
  name: Hosted VS2017

trigger:
  - master

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack Common.Function'
  inputs:
    command: pack
    packagesToPack: LeoPetri.Common.Function/LeoPetri.Common.Function.csproj
    versioningScheme: byEnvVar
    versionEnvVar: PreReleaseVersion

- task: NuGetCommand@2
  displayName: 'NuGet push Common.Function'
  continueOnError: true
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: LeoPetri.Common

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack Common.Domain'
  inputs:
    command: pack
    packagesToPack: LeoPetri.Common.Domain/LeoPetri.Common.Domain.csproj
    versioningScheme: byEnvVar
    versionEnvVar: PreReleaseVersion
    
- task: NuGetCommand@2
  displayName: 'NuGet push Common.Domain'
  continueOnError: true
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: LeoPetri.Common